# Generated by Django 3.0.6 on 2020-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
