# Generated by Django 3.0.6 on 2020-06-16 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boss', '0002_agent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='listing_pics')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villas', 'Villas'), ('Commercial', 'Commercial'), ('Garages', 'Garages')], max_length=200, null=True)),
                ('property_status', models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('number_bedrooms', models.CharField(blank=True, max_length=200, null=True)),
                ('number_rooms', models.CharField(blank=True, max_length=200, null=True)),
                ('number_bath', models.CharField(blank=True, max_length=200, null=True)),
                ('number_garage', models.CharField(blank=True, max_length=200, null=True)),
                ('year_built', models.CharField(blank=True, max_length=200, null=True)),
                ('floor_size', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lon', models.CharField(blank=True, max_length=200, null=True)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
