# Generated by Django 3.0.6 on 2020-06-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
