# Generated by Django 3.0.6 on 2020-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0009_compare_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='female_population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='male_population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
