# Generated by Django 3.0.6 on 2020-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0010_auto_20200626_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('population', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('population', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
