# Generated by Django 3.0.6 on 2020-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0013_insurance_manufacturing_mining'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='covid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='schools',
            field=models.ManyToManyField(to='boss.PrivateSchools'),
        ),
    ]
