# Generated by Django 3.0.6 on 2020-06-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0014_auto_20200628_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateschools',
            old_name='population',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='publicschools',
            old_name='population',
            new_name='admission',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='population',
        ),
        migrations.AddField(
            model_name='privateschools',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='enrolment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='graduates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='enrolment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='graduates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
