# Generated by Django 3.0.6 on 2020-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0015_auto_20200628_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('branchLat', models.CharField(max_length=200)),
                ('branchLon', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='population',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='manufacturing',
            old_name='population',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='mining',
            old_name='population',
            new_name='about',
        ),
        migrations.AddField(
            model_name='bank',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='employment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='employment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='employment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mining',
            name='employment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mining',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(to='boss.branch'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='branches',
            field=models.ManyToManyField(to='boss.branch'),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='branches',
            field=models.ManyToManyField(to='boss.branch'),
        ),
        migrations.AddField(
            model_name='mining',
            name='branches',
            field=models.ManyToManyField(to='boss.branch'),
        ),
    ]
