# Generated by Django 3.0.6 on 2020-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0016_auto_20200628_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
