# Generated by Django 3.0.6 on 2020-07-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0019_region_covidhot_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='covidhot_about',
        ),
    ]
