# Generated by Django 3.0.6 on 2020-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0026_region_economy_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='shs_schools',
        ),
        migrations.AddField(
            model_name='region',
            name='housing_about',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
