# Generated by Django 3.0.6 on 2020-07-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0027_auto_20200702_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='bank',
            field=models.ManyToManyField(to='boss.Bank'),
        ),
        migrations.AddField(
            model_name='region',
            name='insurance',
            field=models.ManyToManyField(to='boss.Insurance'),
        ),
        migrations.AddField(
            model_name='region',
            name='manu',
            field=models.ManyToManyField(to='boss.Manufacturing'),
        ),
        migrations.AddField(
            model_name='region',
            name='mining',
            field=models.ManyToManyField(to='boss.Mining'),
        ),
        migrations.AddField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(to='boss.hospital'),
        ),
    ]
