# Generated by Django 3.0.6 on 2020-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0028_auto_20200702_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='bank',
            field=models.ManyToManyField(null=True, to='boss.Bank'),
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(null=True, to='boss.hospital'),
        ),
        migrations.AlterField(
            model_name='region',
            name='insurance',
            field=models.ManyToManyField(null=True, to='boss.Insurance'),
        ),
        migrations.AlterField(
            model_name='region',
            name='manu',
            field=models.ManyToManyField(null=True, to='boss.Manufacturing'),
        ),
        migrations.AlterField(
            model_name='region',
            name='mining',
            field=models.ManyToManyField(null=True, to='boss.Mining'),
        ),
        migrations.AlterField(
            model_name='region',
            name='private_schools',
            field=models.ManyToManyField(null=True, to='boss.PrivateSchools'),
        ),
        migrations.AlterField(
            model_name='region',
            name='public_schools',
            field=models.ManyToManyField(null=True, to='boss.PublicSchools'),
        ),
    ]
