# Generated by Django 3.0.6 on 2020-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0030_auto_20200702_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
