# Generated by Django 3.0.6 on 2020-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0031_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='median_age',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='num_employees',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='poverty_rate',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
