# Generated by Django 3.0.6 on 2020-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0032_auto_20200702_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='shs_schools',
            field=models.ManyToManyField(blank=True, to='boss.SecondarySchools'),
        ),
    ]
