# Generated by Django 3.0.6 on 2020-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0035_auto_20200702_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateschools',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
