# Generated by Django 3.0.6 on 2020-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0036_auto_20200703_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateschools',
            name='acept_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='acept_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
