# Generated by Django 3.0.6 on 2020-07-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0038_auto_20200703_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateschools',
            name='admission_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='enrol_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='grad_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='admission_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='enrol_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='grad_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
