# Generated by Django 3.0.6 on 2020-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0039_auto_20200703_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_assoprof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_assprof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_instruct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_lec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_nonaca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='num_professor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='opera_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_assoprof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_assprof',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_instruct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_lec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_nonaca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='num_professor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='opera_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='privateschools',
            name='programs',
            field=models.ManyToManyField(blank=True, to='boss.Programs'),
        ),
        migrations.AddField(
            model_name='publicschools',
            name='programs',
            field=models.ManyToManyField(blank=True, to='boss.Programs'),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='programs',
            field=models.ManyToManyField(blank=True, to='boss.Programs'),
        ),
    ]
