# Generated by Django 3.0.6 on 2020-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0041_auto_20200703_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='acaperf_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='admission_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='num_acaperf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='asso',
            field=models.ManyToManyField(blank=True, to='boss.Associations'),
        ),
        migrations.AddField(
            model_name='secondaryschools',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='boss.Facilities'),
        ),
    ]
