# Generated by Django 3.0.6 on 2020-07-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0044_auto_20200703_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='emp_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='emp_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='emp_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mining',
            name='emp_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
