# Generated by Django 3.0.6 on 2020-07-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0045_auto_20200703_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='mining',
        ),
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='branches',
            field=models.ManyToManyField(blank=True, to='boss.branch'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emp_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='employment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='hospital',
            name='revenue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
        migrations.DeleteModel(
            name='Mining',
        ),
    ]
