# Generated by Django 3.0.6 on 2020-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0046_auto_20200703_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
        migrations.AddField(
            model_name='bank',
            name='services',
            field=models.ManyToManyField(blank=True, to='boss.service'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(blank=True, to='boss.service'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='services',
            field=models.ManyToManyField(blank=True, to='boss.service'),
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='products',
            field=models.ManyToManyField(blank=True, to='boss.product'),
        ),
    ]
