# Generated by Django 3.0.6 on 2020-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0049_auto_20200704_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateschools',
            name='admission_about',
        ),
        migrations.RemoveField(
            model_name='privateschools',
            name='cost_about',
        ),
        migrations.RemoveField(
            model_name='privateschools',
            name='enrol_about',
        ),
        migrations.RemoveField(
            model_name='privateschools',
            name='grad_about',
        ),
        migrations.RemoveField(
            model_name='publicschools',
            name='admission_about',
        ),
        migrations.RemoveField(
            model_name='publicschools',
            name='cost_about',
        ),
        migrations.RemoveField(
            model_name='publicschools',
            name='enrol_about',
        ),
        migrations.RemoveField(
            model_name='publicschools',
            name='grad_about',
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
    ]
