# Generated by Django 3.0.6 on 2020-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0052_auto_20200705_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='emp_about',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='rev_about',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='emp_about',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='emp_about',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='rev_about',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='emp_about',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='rev_about',
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
    ]
