# Generated by Django 3.0.6 on 2020-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0053_auto_20200705_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchLat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchLon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
    ]
