# Generated by Django 3.0.6 on 2020-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0057_auto_20200705_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
    ]
