# Generated by Django 3.1.7 on 2021-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0060_auto_20200705_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='boss.Hospital'),
        ),
    ]
